arrowParens: 'always'
bracketSpacing: true
embeddedLanguageFormatting: 'auto'
htmlWhitespaceSensitivity: 'css'
insertPragma: false
bracketSameLine: false
jsxSingleQuote: false
printWidth: 100
proseWrap: 'preserve'
quoteProps: 'as-needed'
requirePragma: false
semi: true
singleQuote: true
trailingComma: 'all'
useTabs: false
tabWidth: 2
vueIndentScriptAndStyle: false
